services:
  - type: web
    name: backend-service
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
# # Di root folder project
# echo 'services:
#   - type: web
#     name: bookworm-backend
#     env: node
#     plan: free
#     rootDir: backend
#     buildCommand: npm install
#     startCommand: npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 10000' > render.yaml
